# Generated by Django 3.2.5 on 2021-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('birthdate', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'division_user_data',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
