# Generated by Django 3.2.5 on 2021-08-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_userdata_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdata',
            table='division_data',
        ),
    ]
