# Generated by Django 3.2.5 on 2021-08-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='')),
                ('asin', models.CharField(max_length=80)),
                ('prices', models.PositiveIntegerField()),
                ('reviews', models.FloatField()),
            ],
            options={
                'db_table': 'division_product',
            },
        ),
    ]
